In the name of Allah

In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

In [62]:
df = pd.read_csv("./../data/sample_data.csv")
df = df.drop([df.columns[0], df.columns[1]], axis=1)
df['cat1'] = df['cat1'].fillna('Unknown')
df['cat2'] = df['cat2'].fillna('Unknown')
df['cat3'] = df['cat3'].fillna('Unknown')
df['type'] = df['type'].fillna('Unknown')
df.head()

archive_by_user                  brand             cat1  \
0             True  پژو ۲۰۶‍::Peugeot 206         vehicles   
1            False                    NaN  leisure-hobbies   
2             True                    NaN     for-the-home   
3            False                    NaN         personal   
4             True                    NaN     for-the-home   

                        cat2                 cat3     city      created_at  \
0                       cars                light   Shiraz   Thursday 06PM   
1                    animals         farm-animals    Karaj   Saturday 07AM   
2  furniture-and-home-decore        sofa-armchair   Tehran   Thursday 08AM   
3              baby-and-toys  childrens-furniture  Mashhad     Sunday 10AM   
4  furniture-and-home-decore    tables-and-chairs   Tehran  Wednesday 02PM   

                                                desc              id  \
0  بیرنگ و خط وخش...تیپ 2 قیمت کاملا مقطوع. اصلا ...  65162744622027   
1  1عددخروس با مرغش.فوقولاده سرحال.خروس از جوجگی ...  54131487310980   
2  ٢ عدد مبل میزبان \n٤ عدد مبل دو دسته \nیک عدد ...  31291571262425   
3                       لباسشویی مارک بسیار خوب و نو  17458250713790   
4    میز نهار خوری کاترین ۴ نفره. چوب روس . در حد نو  33350431482856   

   image_count   mileage platform     price  \
0            0  130000.0   mobile  21000000   
1            1       NaN   mobile        -1   
2            5       NaN   mobile   1500000   
3            2       NaN   mobile        -1   
4            1       NaN   mobile    350000   

                                    title     type    year  
0               206سفیدتمام فابریک87تکبرگ  Unknown  1387.0  
1                               خروس لاری  Unknown     NaN  
2  مبلمان نه نفره با میز ناهارخوری ٨ نفره  Unknown     NaN  
3                       لباسشویی کهنه شور  Unknown     NaN  
4              میز نهارخوری ۴ نفره کاترین  Unknown     NaN

In [63]:
df = df[["brand", "cat1", "cat2", "cat3", "city", "desc", "mileage", "price", "title", "type", "year"]]
df

brand                cat1                       cat2  \
0    پژو ۲۰۶‍::Peugeot 206            vehicles                       cars   
1                      NaN     leisure-hobbies                    animals   
2                      NaN        for-the-home  furniture-and-home-decore   
3                      NaN            personal              baby-and-toys   
4                      NaN        for-the-home  furniture-and-home-decore   
..                     ...                 ...                        ...   
995                    NaN            personal              health-beauty   
996                    NaN  electronic-devices                  computers   
997                    NaN            vehicles          parts-accessories   
998                    NaN        for-the-home    utensils-and-appliances   
999                    NaN            personal         clothing-and-shoes   

                      cat3        city  \
0                    light      Shiraz   
1             farm-animals       Karaj   
2            sofa-armchair      Tehran   
3      childrens-furniture     Mashhad   
4        tables-and-chairs      Tehran   
..                     ...         ...   
995                Unknown     Mashhad   
996  parts-and-accessories      Tehran   
997                Unknown      Shiraz   
998     fridge-and-freezer     Mashhad   
999         shoes-belt-bag  Kermanshah   

                                                  desc   mileage     price  \
0    بیرنگ و خط وخش...تیپ 2 قیمت کاملا مقطوع. اصلا ...  130000.0  21000000   
1    1عددخروس با مرغش.فوقولاده سرحال.خروس از جوجگی ...       NaN        -1   
2    ٢ عدد مبل میزبان \n٤ عدد مبل دو دسته \nیک عدد ...       NaN   1500000   
3                         لباسشویی مارک بسیار خوب و نو       NaN        -1   
4      میز نهار خوری کاترین ۴ نفره. چوب روس . در حد نو       NaN    350000   
..                                                 ...       ...       ...   
995  سلام یک ماشین اصلاح نو مارک موزر ژرمنی که توعک...       NaN     70000   
996  باتری قلمی میخوره\nاتصال از طریق بلوتوث خیلی ر...       NaN     25000   
997  ظبط دمو دار$NUMپانل برقی فلاش  از پشت میخوره  ...       NaN        -1   
998  با مارک امرسان به علت محاجرت و دو عدد ماشین لب...       NaN    420000   
999             3تاکیف زنانه جهت فروش تخفیف ریزهم داره       NaN     25000   

                                      title     type    year  
0                 206سفیدتمام فابریک87تکبرگ  Unknown  1387.0  
1                                 خروس لاری  Unknown     NaN  
2    مبلمان نه نفره با میز ناهارخوری ٨ نفره  Unknown     NaN  
3                         لباسشویی کهنه شور  Unknown     NaN  
4                میز نهارخوری ۴ نفره کاترین  Unknown     NaN  
..                                      ...      ...     ...  
995                 ماشین اصلاح ژرمنی(موزر)  Unknown     NaN  
996                              ماوس بیسیم  Unknown     NaN  
997                ظبط دمو دار$NUMپانل برقی  Unknown     NaN  
998                             یخچال فریزر  Unknown     NaN  
999                               کیف زنانه    women     NaN  

[1000 rows x 11 columns]

In [65]:
np.unique(list(df['year']))

array([1366., 1371., 1372., 1374., 1376., 1377., 1378., 1379., 1380.,
       1381., 1382., 1383., 1384., 1385., 1386., 1387., 1388., 1389.,
       1390., 1391., 1392., 1393., 1394., 1395.,   nan])

In [32]:
y_data = df[["cat1", "cat2", "cat3"]]
x_data = df[["brand", "city", "desc", "mileage", "price", "title", "type", "year"]]

In [29]:
pd.get_dummies(df["cat3"]).columns

Index(['accessories', 'antiques-and-art', 'ball-sports',
       'barbershop-and-beautysalon', 'bathroom-wc-sauna', 'beds-bedroom',
       'birds', 'cafe-and-restaurant', 'camera-camcoders', 'camping-outdoor',
       'carpets', 'child-car-seat', 'childrens-furniture', 'clothing',
       'coin-stamp', 'cookware-tableware', 'desktops', 'educational',
       'farm-animals', 'fridge-and-freezer', 'garden-and-patio', 'heavy',
       'historical-objects', 'industrial', 'instrument-cleaning-tailoring',
       'jewelry', 'kitchen', 'laptops', 'light', 'lighting', 'microwave-stove',
       'mobile-phones', 'mobile-tablet-accessories',
       'modem-and-network-equipment', 'offices', 'parts-and-accessories',
       'personal-toys', 'piano-keyboard', 'printer-scaner-copier',
       'repair-tool', 'rodents-rabbits', 'shoes-belt-bag', 'shop-and-cash',
       'sofa-armchair', 'stereo-surround', 'storage', 'stove-and-heating',
       'strollers-and-accessories', 'tables-and-chairs', 'tablet',
       '

In [25]:
d = pd.get_dummies(df["cat1"]).to_numpy()
d[0]

array([0, 0, 0, 0, 0, 1], dtype=uint8)

In [33]:
enc = OneHotEncoder()

In [34]:
res = enc.fit_transform(y_data).toarray()

/Users/m213/Library/anaconda3/envs/my-conda-env/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:808: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [36]:
res[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [62]:
enc.inverse_transform([res[995]])

array([['personal', 'health-beauty', nan]], dtype=object)